sudo: required
dist: trusty
group: deprecated-2017Q4
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- git config --global user.email "contact.ajanin@gmail.com"
- git config --global user.name "Alexandra JANIN"
script:
- npm test
env:
  global:
  - USE_YARN=no
  - CI=true
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  npm run deploy; fi
deploy:
  provider: releases
  api_key:
    secure: bVUp+X2da7NVfD2LOWI3F19HEufzveSC5VbISMCeWe2jNHAR1nmEZuy6NQyNqdPQpG0vt/dLCzza6fDyjY4BW6pI5kpomaIjPSmLtop/gWVmBtTTSL71+OZrUbzjhRnAAh6Zqmy2iwhGlxJ42NTqbe9rdzozwT68MusOTXGZLps=
  file_glob: true
  file: "build/*/**"
  skip_cleanup: true
  on:
    repo: sudweb/talks
    tags: true
