language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
  - git config --global user.email "contact@sudweb.fr"
  - git config --global user.name "Travis-CI"
script:
 - npm test
env:
  global:
    - USE_YARN=no
    - CI=true
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy; fi
