sudo: required
dist: trusty
group: deprecated-2017Q4
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- git config --global user.email "contact.ajanin@gmail.com"
- git config --global user.name "Alexandra JANIN"
script:
- npm test
env:
  global:
  - USE_YARN=no
  - CI=true
  - secure: KHRYfQu/Hq1ogOUIAzSKMvg17I1GY4F0WwVM/eYRaXA6rO4PKT5RYAHj7DJdWjR4D6tYD3+F6NoAMluYHWP5/YR/pg5CqHs+KqmAJ2w8M+pFHAXF3nIXP0xsOrkgQON3AXJrZpZA3Ol3JG+7ORyg9MeGwV0VOpR+20J2gkBBV34=
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  npm run deploy; fi
deploy:
  provider: releases
  file_glob: true
  file: build/*/**
  skip_cleanup: true
  on:
    repo: sudweb/talks
    tags: true
